### PR TITLE
Documentation suggestions

### PR DESCRIPTION
**Pull request by dr-shorthair**
A few suggestions to clarify the documentation. 
Possible changes to property-names: 
- featureOfInterest --> hasFeatureOfInterest
- sample --> sampleOf
  Possible change to definition of 'Observation'

### CODE REVIEW

**Comment by arminhaller** [comment]
Agree to Simon and in the same spirit:

phenomenonTime -> hasPhenomenonTime
resultTime -> hasResultTime

Otherwise looks great, we have something to go back to the group tomorrow!

**Comment by kjano** [comment]
I like the has versions as well but didn't somebody object to them before?

**Comment by kjano** [comment]
Btw, do you also get errors opening the file in topbraid composer? everything works fine but it returns a 'Multiple children of property element' error. I do my edits in sublime (with rdf/ttl highlighting package) but used topbraid today.

**Comment by arminhaller** [comment]
I guess maybe the naming compatibility to SSN may be an issue. SSN seems to be not entirely consistent, for example, using featureOfInterest rather than the hasFeatureOfInterest. We may need to "inherit" that.

One thing I forgot to mention before, although we are currently not doing it anyway. We should definitely not import schema.org (I suggest to even make up our own annotation properties rather than reusing them as we have done initially for the domain/range annotations) in the core for two reasons:
- Simplicity
- Schema.org is not exactly following the principles of ontology engineering, i.e. not importing any prior ontologies, but just copying classes/properties. I don't think we should give them the courtesy to do the reverse, importing schema.org.

**Comment by dr-shorthair** [comment]
> do you also get errors opening the file in topbraid composer?

I did earlier today, but not now. 

Generally find TopBraid's ttl to be very clean, the only issues being 
(i) excessive number of @prefix declarations at the top of the file.,
(ii) gratuitous creation of an owl:Ontology resource, corresponding to the file, which TopBraid uses to support its graph management.  
I'm happy to work around both of those. 

I've just started using Sublime (previously Brackets and before that Ultraedit). Nice.

**Pull request merged**
