### PR TITLE
Fix reference after removal of "how to use" section

### PR DESCRIPTION
**Pull request by cportele**

### CODE REVIEW

**Comment by 6a6d74** [comment]
@cportele 

I'll merge this & then make another change ... ReSpec is clever enough to fill in the text for a <a> element. Also, we're using `class="sectionRef"` to style these links.

**Comment by cportele** [comment]
@6a6d74 Oh thanks, when we are done I will have understood ReSpec ;)

**Comment by 6a6d74** [comment]
They keep changing it! And I only understand the bits I use :-)

**Comment by 6a6d74** [comment]
See PR #842 

```
<a href="http://w3c.github.io/sdw/bp/#bp-exposing-via-api">section 12.3 Spatial data access</a> 
```

becomes:

```
<a href="#bp-exposing-via-api" class="sectionRef"></a>
```

**Comment by cportele** [comment]
I see - will use that in future. Thanks!

**Pull request merged**
