### PR TITLE
Lvdb gaps

### PR DESCRIPTION
**Pull request by lvdbrink**
This PR addresses part of the issues coming out of my analysis of the Gaps section (#1292, #1259). It only focusses on paragraph 13.1 of the Gaps section.

- Removed first paragraph of 13.1 about the question of different serialization formats to choose from
- Removed 13.1 paragraph about CRS conneg
- Addition to BP8: a fifth way to provide CRS information to the user (using OGC API Features part 2)
- Addition of new BP Support requesting and returning geometries in a specific requested CRS

See #1259 for argumentation.

### CODE REVIEW

**Comment by situx** [comment]
A general question when reviewing this:

Are we using the term CRS or SRS, and is there a valid reason for that if we are using CRS?

You are still missing one GeoSPARQL example which could look like the one below which filters by CRS84:

SELECT ?geo_wkt WHERE {
  ?geo geo:asWKT ?geo_wkt .
  FILTER(geof:getSRID(?geo_wkt)==<http://www.opengis.net/def/crs/OGC/1.3/CRS84>)
}

Apart from that I think the text is good!

**Review by situx — CHANGES_REQUESTED** [review]
GeoSPARQL example is still missing and a question concerning the use of the term SRS and how to deal with e.g. Geocoding as something that does not indicate a CRS could be helpful

**Comment by andrea-perego** [comment]
> You are still missing one GeoSPARQL example which could look like the one below which filters by CRS84:
> 
> SELECT ?geo_wkt WHERE {
> ?geo geo:asWKT ?geo_wkt .
> FILTER(geof:getSRID(?geo_wkt)==http://www.opengis.net/def/crs/OGC/1.3/CRS84)
> }

About the example, I wonder whether `geof:getSRID` returns the SRS also when it is not explicitly specified in the geometry literal (excuse my ignorance).

Shouldn't this be the case, it would be probably better to revise the example to use either another SRS or another geometry literal encoding.

**Comment by situx** [comment]
In GeoSPARQL 1.0 the situation is as follows:
- WKT Literals without a CRS definition are assumed to use the CRS84 CRS
- GML Literals without a CRS definition are allowed but would probably fail the test of a GML parser (not sure though)

In GeoSPARQL 1.1 the situation will be as follows:
- GeoJSON literals and KML literals have a fixed CRS by definition of the literal format
- DGGS literals without a CRS definition are to my knowledge not defined correctly, so they should not parse correctly

The specification (GeoSPARQL 1.0 and 1.1) only says that the CRS of the geometry literal is to be returned. How to treat errors is up to the implementers to a certain extent.
I believe that the triple store would return a general error message here.

**Comment by lvdbrink** [comment]
Added the GeoSPARQL example provided by @situx above. 

> Are we using the term CRS or SRS, and is there a valid reason for that if we are using CRS?

Currently the test is predominantly using the term CRS and I think appropriately, because we are talking about coordinate reference systems. In the context of requesting data in a specific reference system (which this PR is about), CRS is the correct term as we mean to talk about coordinate reference systems. However, I can see the benefit in talking about spatial reference systems in the larger context of the BP document. But this would be a separate issue.

**Review by BillSwirrl — COMMENTED** [review]
Hi Linda, your updates look good to me.  I only have some minor comments and suggestions.

bpconfig.js line 255.  "Clements" should be "Clemens"

New example on Content-crs HTTP header in BP8 looks good

New best practice "Support requesting and returning geometries in a specific CRS":

Line 3787

I would suggest being less detailed on the mechanics of re-projection, because there could be lots of ways to do it.  Suggested alternative (not perfect either, so feel free to use, edit or ignore as you like!)

 <p>Offering geospatial data in different <a>CRS</a> in practice means the data needs to be transformed from the original <a>CRS</a> to other supported <a>CRS</a>s. Database software and libraries for most programming languages are available which can do this.  Reprojection can be done in advance and stored, or calculated at the time of a request. If reprojecting on request, since geographic data can be large and complex, it is recommended to cache the converted data to eliminate the need of reprojecting the same data more than once. </p>
 
 The example that goes with this is really useful.
 
 And I agree the updates to  the 'different representations of geometries' section is an improvement.

**Comment by lvdbrink** [comment]
@situx is it okay to merge given my reply to your review?

**Review by situx — APPROVED** [review]

**Comment by situx** [comment]
Looks good to me Linda. Should be ready to merge

**Pull request merged**
