### PR TITLE
ACTION-278: add change history for updates since 2nd PWD until 21st,March

### PR DESCRIPTION
**Pull request by danhlephuoc**
I tracked down the closed PRs back to 5th, January, 2017, I was confused with PR https://github.com/w3c/sdw/pull/572 which contains several changes addressing several issues, I'm not sure I missed something.

### CODE REVIEW

**Review by dr-shorthair — COMMENTED** [review]
> Change any mention of owl:inverseOf into schema:inverseOf

I hadn't noticed this, but it makes sense. But presumably only applies to SOSA? 

> Add ObservableProperty and ActuablePropery

*ActuatableProperty*

> Change sosa:madeByActuator to sosa:actuationMadeBy

Hmmm. This becomes inconsistent with comparable properties for observation and sampling.

**Comment by arminhaller** [comment]
Please note that we have not changed the owl:inverseOf in SOSA to schema:inverseOf. There was no such decision made and SOSA still uses owl:inverseOf.

**Review by maximelefrancois86 — COMMENTED** [review]
> 2. Change any mention of owl:inverseOf into schema:inverseOf

As far as I can remember, the pull request I proposed that was named like this has been accepted, then reverted. SOSA still uses owl:inverseOf.

> 4. Fix minor errors in sosa.ttl and ssn.ttl

Could that be a little more precise, or be deleted ?

> 7. Address naming consitency with isObservedBy/observes,madeBySensor/madeObservation

little typo (consistency). 

> 10.1 Add sosa:Actuation to domain/range of result properties

domain and range ? in sosa :-)

> Rename invokes and invokedBy to madeActuation and madeByActuator

indeed, as Simon said, that's inconsistent with madeBySensor/madeObservation. As shown on figure https://www.w3.org/2015/spatial/wiki/File:20170308-foi-property-object-event.png 

> Add hasSimpleResult instead of hasValue

Should mention there is sosa:hasResult instead of ssn:hasValue, and sosa:hasSimpleResult instead of sosa:hasValue ?

> Add ObservableProperty and ActuablePropery

ActuatableProperty ?

**Comment by arminhaller** [comment]
@danhlephuoc could you please address the issues as above and recommit? Also, please try to use an editor that does not make line break changes so that it becomes clear that the only change that was made has been the change to the "change history".

**Comment by arminhaller** [comment]
As of Maxime's comment, it should be  schema:domainIncludes and schema:rangeIncludes.
We do have sosa:actuationMadeBy and sosa:madeActuation and sosa:madeBySensor and sosa:madeObservation in SOSA. This is not entirely consistent, but due to legacy. And we agreed to leave it like that.
It should be ActuatableProperty as maxime pointed out.

**Pull request closed without merging**
