### PR TITLE
Best Practice 11- added 

### PR DESCRIPTION
**Pull request by PBarnaghi**
Best Practice 11- added

### CODE REVIEW

**Comment by 6a6d74** [comment]
Hi @PBarnaghi ... looks like you've merge conflicts on this PR. I will try to resolve; could be tricky though. 

Looking at the commit history I see `Merge branch 'gh-pages' into bp-edit-payamb` ... did you `pull` gh-pages or `rebase`? My preference is to `rebase` as it doesn't create these point commits.

**Comment by PBarnaghi** [comment]
Hi Jeremy, sorry about this; I pulled gh-pages but didn't do any merge.

Thanks,
Payam

**Comment by 6a6d74** [comment]
ok ... I'm working through unpicking things. J

**Comment by 6a6d74** [comment]
closing this PR without merge; superseded by PR #104 

(well, actually, this PR was included in PR #104)

**Comment by PBarnaghi** [comment]
Hi Jeremy, Linda,

I completed my BPs but when I synced the latest version. It seems some of
my updates are lost and the formatting has also been mixed up.

Do you know what happened?

Thanks,
Payam

**Comment by 6a6d74** [comment]
Hi Payam, all fixed now. You should be able to continue.

That said, I thought I would just check your git / github workflow.

[ref. http://www.w3.org/2015/spatial/wiki/How_to_work_with_GitHub] ...
1. create a local copy of the W3C SDW repo: git clone
   https://github.com/w3c/sdw.git
2. configure remotes on local - specify the W3C repo remote as
   `upstream`: git remote add upstream https://github.com/w3c/sdw.git
3. because we're using GitHub Pages for publication, `gh-pages` is our
   main branch
4. create a branch in your local repo which tracks gh-pages in upstream:
   git checkout -b {my-branch-name} upstream/gh-pages
5. make the changes in your branch & commit - with commit message please!
6. synchronise your changes with upstream: git push upstream
   {my-branch-name}
7. within GitHub, create a Pull Request from {my-branch-name} into
   gh-pages ... at this point, you might assign the PR to someone else to
   check before merging
8. _EDITORS ONLY_: within GitHub, Merge the changes into gh-pages ...
   then you will see your stuff @ http://w3c.github.io/sdw/bp/
9. bring all those changes back into your local repo: git fetch upstream
10. rebase (don't 'pull' - because this creates another commit) changes
    on your branch: git rebase upstream/gh-pages

You can check your remotes with the following command:

git remote -v
... the response I get is:

origin https://github.com/6a6d74/sdw.git (fetch)

origin https://github.com/6a6d74/sdw.git (push)

upstream https://github.com/w3c/sdw.git (fetch)

upstream https://github.com/w3c/sdw.git (push)

w3c https://github.com/w3c/sdw.git (fetch)

w3c https://github.com/w3c/sdw.git (push)

You can see that I get (fetch) and (push) permissions on the remote
repositories. I've configured `origin` to refer to the repo on my own
github account and both `upstream` and `w3c` to refer to the official W3C
repo. Use of `upstream` is just a habit I have; that's always the name I
use for the collaboration repo.

_Before_ you make any edits ... and after each `commit` in your editing
branch (`bp-edit-payamb`) get changes from the `upstream` repo and REBASE
from the `gh-pages` branch into your editing branch:

git fetch upstream
git rebase upstream/gh-pages

This should mean you avoid getting out of sync.

Happy to talk though this on the phone if you want tomorrow.

Jeremy

**Comment by PBarnaghi** [comment]
Hi Payam- if some things are missing its because I had to manually decide
what to include when I reconciled the merge conflict. Apologies.

Jeremy

**Comment by PBarnaghi** [comment]
Thanks Jeremy. It seems I have lost all my updates since this morning; but
I think I still have drafts of some of what I wrote and will write again;
thanks for fixing the issues and my apologies if I mixed up something on
the github.

**Comment by 6a6d74** [comment]
I only saw the 4 commits in PR 92; nothing from this morning. If you can
find the drafts of what you wrote this morning it should be easy enough to
overlay them- if a little time consuming.

**Comment by PBarnaghi** [comment]
I have attached it to this email. This should include all the BPs from
11-18; the version on Github does not include 16, 17, 18;
Can you please merge the BP16, 17, 18; and then I will delete my local
repository and will synchronise everything from scratch;

@My BPs are done; I will now move to the scope section.  let me know if you
need help with some other BPs (I can write a few more by next week).

Thanks,
Payam

**Comment by 6a6d74** [comment]
I'll see what I can do; but it won't happen until tomorrow. J

**Pull request merged**
