### PR TITLE
Proposed extension to OWL-Time - Time aggregates

### PR DESCRIPTION
**Pull request by dr-shorthair**
Preview at https://rawgit.com/w3c/sdw/time-aggregates/proposals/time-aggregates/index.html

### CODE REVIEW

**Comment by chris-little** [comment]
@dr-shorthair, @lvdbrink  I was wondering why in the Turtle, the Skos declaration for the German language has the month in lower case, but all the others in upper case?   "skos:prefLabel "monat"@de ;" 

and in Polish why is the year in upper case and all the others in lower?   "skos:prefLabel "Rok"@pl ;"

These are typos. I have just checked with two native speakers - not subtleties of their languages.

I am assuming the Turtle tool has put everything in Unicode collation order.

**Comment by chris-little** [comment]
Section 2, first sentence in the final document is missing 'ontology' "Classes and properties from the are denoted..."

In "4.1.1 Temporal aggregate" , and in Figure 1, is the name of the super class really "Sub-class of: | time:hasPart min 1" ?  No other entities have a cardinality built into the name.

**Comment by dr-shorthair** [comment]
@chris-little those typos are in OWL-Time published three years ago! Not the time-aggregates extension. Would be good to fix, but please put in a separate issue.

**Comment by dr-shorthair** [comment]
Section 2- thanks. 
4.1.1 - it is a Restriction - I've made that clear now.

**Comment by dr-shorthair** [comment]
The document can be viewed at https://w3c.github.io/sdw/proposals/time-aggregates/ so I will delete the branch now.

**Pull request merged**
