### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by kjano**
A proposal for an updated text for hasMember.

### CODE REVIEW

**Review by dr-shorthair — APPROVED** [review]

**Comment by kjano** [comment]
I saw that you approved the change. Thanks a lot. I do not want to mess with your workflow; should  I merge or will you or Linda?

**Comment by dr-shorthair** [comment]
Process has been a bit loose in these byways. 
Would be good for @lvdbrink or @jabhay to be aware of this work, so let's ask them. 

Would be good to fold ssn-ext into vocab-ssn, but I don't think we can do that without chartering a new W3C working group. 

Meanwhile, CSIRO has let its membership of W3C lapse, after ca. 25 years. I was responsible for the organization joining in 1996 or thereabouts, but it has been with the computer scientists for the last 20, and they have lost interest. So I will have to manage my status to be able to continue to contribute ...

**Comment by kjano** [comment]
@dr-shorthair Oh! I had no idea about the W3C issue :-(. Should I sync these changes we made with the RDF file, so far they are only in the documentation, correct?

**Comment by dr-shorthair** [comment]
I think it is OK in the files now - https://github.com/w3c/sdw/blob/gh-pages/ssn/integrated/examples/tree-height.ttl#L57 

I did get bamboozled by Francois' HTML tricks though.

**Comment by lvdbrink** [comment]
Perhaps @tidoust could help us out here...

**Pull request merged**
