### PR TITLE
add back spacing in dul alignment for 3rd time

### PR DESCRIPTION
**Pull request by KerryLea**

### CODE REVIEW

**Comment by arminhaller** [comment]
Please do not use whitspaces or back spacing in the code environment. In a collaborative setting like Git this is doomed to break every time someone makes a change. Please use CSS styles for indentation.

**Comment by KerryLea** [comment]
Any editor that changes document whitespace should be banned as can automatically hide all significant changes from a diff listing, even when whitespace is irrelevant.
 This  method applied here is  conformant with (recommended in)  HTML5.1 November 2016.
Comparable CSS styling appears to be unreadable and unwritable without special tooling.

**Comment by KerryLea** [comment]
Other SDW deliverables also use this method without problems.

**Comment by danhlephuoc** [comment]
@KerryLea and @arminhaller , what is the conclusion for this PR? There are conflicts in this PR but looking into the changes, it's not really big, should some one to review it again to merge?

**Comment by KerryLea** [comment]
Thks for asking. Armin did not like it – and I have fixed it in a later PR (that you have already merged). #475
I will  promptly close this one you asked about.

I am going to have one more attempt to do the spacing again now  the way Armin wants (no space characters) . But If  I run out of time, afaiac, what you have done already will do.

--Kerry

**Pull request closed without merging**
