### PR TITLE
Proposed alignments between SOSA and O&M

### PR DESCRIPTION
**Pull request by dr-shorthair**
1. Two RDF files holding alignment axioms for SOSA <-> O&M (ISO 19150-2 URIs, om-lite)
2. Proposed text for document explaining the alignment

### CODE REVIEW

**Comment by dr-shorthair** [comment]
Superseded by subsequent discussion on the list.

**Comment by kjano** [comment]
@dr-shorthair  "Superseded by subsequent discussion on the list." --> Can you give us some more details?

**Comment by dr-shorthair** [comment]
There has been clear pushback regarding putting RDF artefacts in the repo which have not been exhaustively discussed on Wiki and email list. 
My intention was only to provide concrete artefacts for discussion, but if this conflicts with group process then maybe need to hold off.

**Comment by dr-shorthair** [comment]
OK - re-opening in response to requests from two of the editors. 

Recent changes to gh-pages merged in and deconflicted. 
The four ttl files all have annotations to clarify their status. 
Chapter 8 text removed from draft document, replaced with a link the Wiki page holding the proposal.

**Comment by dr-shorthair** [comment]
note that this commit chain bridged the rename of ssn.owl to ssn.ttl, and duelling commits make it look like there are a lot of lines from ssn changed. But actually **nothing** relative to the current head.

**Pull request merged**
