### PR TITLE
[CovJSON] Fixed logos and publication rules errors on the way to FPWD

### PR DESCRIPTION
**Pull request by tidoust**
- Logos and copyright updated
- Some HTTP URIs need to be HTTPS URIs
- An image did not have an alt text
- Fixed a couple of broken links as well

### CODE REVIEW

**Comment by jonblower** [comment]
Looks good, but I would suggest changing the alt-text of the tiled NdArray (line 243 of index-html) to:

"Illustration of a tiled NdArray. The data array is split into a number of tiles, each of which will be represented by a separate CoverageJSON file"

Apart from this, I'm happy to accept the changes.

**Comment by tidoust** [comment]
@jonblower I updated the alt-text as suggested.

**Review by BillSwirrl — APPROVED** [review]
Thanks Francois - changes look fine to me.

**Comment by jonblower** [comment]
Thanks @tidoust I approve this too but, er, I'm not sure how. Do I "Merge pull request"? I was looking for an "approve" button but I can't find one!

**Comment by tidoust** [comment]
Yes, @jonblower, "Merge pull request" is the easiest. I can do it, but since I can tell that you would love to play with GitHub, I'll leave that up to you ;)

**Pull request merged**
