### PR TITLE
Updated sosa-ssn alignment

### PR DESCRIPTION
**Pull request by dr-shorthair**
I updated the ssn-sosa.ttl graph to reflect refined understanding from the last week's email discussions. 

Note that owl:equivalentClass/Property relations indicate potential opportunities to streamline SSN by adopting the SOSA resources directly, alongside an import of SOSA. 

Included comments for sub-class and sub-property relationships to explain why.

### CODE REVIEW

**Review by maximelefrancois86 — DISMISSED** [review]
> Not clear how to relate this to ssn:hasValue, which is an owl:ObjectProperty

indeed, `sosa:hasValue` and `oldssn:hasValue` are of different types. 

OWL forbids us to align them in any ways.

Anyways, now that ObservationResult and SensorOutput are merged into Result, shouldn't we get rid of ssn:hasValue altogether ?

**Review by maximelefrancois86 — COMMENTED** [review]
sosa:ObservableProperty
 rdfs:comment "ssn:Property is super-class of all properties including those that are not necessarily 'observable'. " ;
 rdfs:subClassOf ssn:Property ;

--> OK, conform to the proposed solution for ISSUE-87

**Review by maximelefrancois86 — COMMENTED** [review]
ssn:FeatureOfInterest
   owl:equivalentClass sosa:FeatureOfInterest ;

--> OK

**Review by maximelefrancois86 — CHANGES_REQUESTED** [review]
If prefix ssn refers to the old ssn
 -> change prefix declaration to http://purl.oclc.org/NET/ssnx/ssn#

Else, if prefix ssn refers to the new ssn
 -> I think we agreed there should be no redefinition of ssn:Xyz when there exists sosa:Xyz ?

**Comment by dr-shorthair** [comment]
The intention of this alignment file was to document the potential equivalentClass/Property and sub-Class/Property relationships. 
A file already exists in GitHub which needs updating to reflect discussions in the last week. 

The URIs/namespaces reflect the **current** state of the ontology in the file ssn.ttl and sosa.ttl. 
If these change in future, then this alignment should be changed, but corresponds with the current state of the repository. 

Lets not get tangled up here - the concerns Maxime expresses are valid, but their resolution belongs in future commits. This pull request should be accepted as-is since it is consistent with the current state of sosa.ttl and ssn.ttl 

As mentioned in the pull-request, where we agree that the relationship is indeed equivalentClass/Property, then there is an option to remove the ssn:Xyz in favour of sosa:Xyz.

**Pull request merged**
