### PR TITLE
[time] Fix the language tags of japanese literals to be @ja

### PR DESCRIPTION
**Pull request by white-gecko**

### CODE REVIEW

**Review by chris-little — COMMENTED** [review]
Looks good. but no idea what would break. Probably originally a confusion between ISO 639-1 and ISO3166. And ISO639-2 using `jpn` doesn't help.

**Comment by white-gecko** [comment]
I don't know if something would break, at the moment it is used inconsistently, sometimes ja, sometimes jp.

**Comment by dr-shorthair** [comment]
Shouldn't break anything in term of logic and semantics. These are annotations. Might affect some user-interfaces.

**Comment by dr-shorthair** [comment]
@white-gecko can you resolve these conflicts please?

**Comment by white-gecko** [comment]
I have rebased it.

**Review by dr-shorthair — APPROVED** [review]

**Pull request merged**
