### PR TITLE
Update MapML roadmap categorizations with examples

### PR DESCRIPTION
**Pull request by prushforth**
MapML responds to several categories in the roadmap analysis. I've tried to add it in where it would not seem like I'm trying to put it where it doesn't belong, but where I think there are solid examples and / or use cases.

### CODE REVIEW

**Review by lvdbrink — COMMENTED** [review]
I can't read the link you provided with 'GeoWeb input forms in MapML'. I assume it's a closed Github repo. Can you provide the information so I can complete my review?

**Comment by prushforth** [comment]
Ah yes, someone duplicated that so I closed the issue and redirected to their issue.  The new link is: https://github.com/opengeospatial/D012-MapML_Engineering_Report/issues/26

**Review by lvdbrink — COMMENTED** [review]
Could you explain in what way MapML is a way to represent spatial data? I.e. is it more than a way to present a view, does it provide a data format?

**Comment by prushforth** [comment]
@lvdbrink Yes I will have a go at that. MapML does indeed provide access to vector and attribute data.  

For example, here is a[ feed of MapML for Canadian Topographic vector information encoded in MapML](https://geogratis.gc.ca/api/beta/vectors/canvec/50k/features/?zoom=18&xmin=-74.83370999540365&ymin=45.55252309288624&xmax=-74.7879392566875&ymax=45.56976806445436&projection=WGS84&entry-type=full&alt=xml).

**Comment by prushforth** [comment]
Although the vector demo application is having problems due to unresolved CORS issues at the current time, you may be able to visualize that feed on another map.

Instructions:

1. Open [this map](http://geogratis.gc.ca/api/beta/mapml/en/cbmtile/cbmt/#17,-74.8103858,45.5627348)
2. Drag [this URL](https://geogratis.gc.ca/api/beta/vectors/canvec/50k/features/) onto that map
3. Visualize vector MapML data, with any luck

**Comment by prushforth** [comment]
I fixed the link, but that line was in conflict with another for some reason. I kept both lines.

**Pull request merged**
