### PR TITLE
Add BP about responsible use of spatial data

### LINKED ISSUE #1146: Should the best practices mention ethical use of geo, and if so how?
Raised during discussion of WebVMT at OGC Toulouse TC with @rjksmith 

WebVMT files provide map presentation and annotation synchronised to video content, including animation support, and more generally any form of geolocation data that is time-aligned with audio or video content.

This creates a potential issue of facial recognition combined with geospatial information knowing exactly who and where someone is. Therefore should the best practices talk about how geo should be integrated into the web in an ethical way?

### PR DESCRIPTION
**Pull request by lvdbrink**
Relates to #1284.

@EmilyDaemen gave me the contents for this best practice. Before this is ready for merging we need to:
- figure outwhere in the document to fit this in. I think at least it should go in chapter 12 The best practices. For now I inserted it at the end of that chapter. Perhaps we should embed it in a new section "spatial data creation" or "spatial data ethics" or similar. 
- review the contents.

### CODE REVIEW

**Comment by situx** [comment]
I think the text is good. However, there is still a comment "needs updating" in the text. Is there something missing?

**Comment by situx** [comment]
Closes #1284

**Comment by lvdbrink** [comment]
> I think the text is good. However, there is still a comment "needs updating" in the text. Is there something missing?

I removed the comment, moved the new BP to its own section as discussed in our meeting last week, and also added a small intro to this new section.

**Review by situx — APPROVED** [review]
Great! Seems good to me.

**Pull request merged**
